### ISSUE TITLE
Yeah I have an issue regarding the admins of this server

### ISSUE THREAD

**Issue by RoleplayRascal** [chaosyourgod/-tg-station#10]
They're fucking gay. I'd rather have koriath and puppysky as the staff of the server than these two fucking losers.
Chaosyourgod? he's a fucking 4am loving loser
8chanserverhost? He doesn't even HOST the server. He misses a mark for having 8chan in his name.
thanks for reading

**Comment by RoleplayRascal** [comment]
upvoted for speaking the truth
i'd give reddit gold but github is worse than reddit
i can't even look at your post history!

**Comment by DoctoreMad** [comment]
Ironic shitposting is still shitposting.

**Comment by DoctoreMad** [comment]
Also everyone knows you're the server host

**Comment by RoleplayRascal** [comment]
Woah, If I was the server host, I'd do myself a favour and shoot myself. 
Also you've been upvoted for speaking the truth

**Comment by Sierracode** [comment]
Who is this roleplayrascal fag. And why is he not in a discord with a rat fucker being autistic and playing Seige with me.
