### ISSUE TITLE
some kind anon has the forced anonymuse ckey code which was done

### ISSUE THREAD

**Issue by chaosyourgod** [chaosyourgod/-tg-station#15]
https://pastebin.com/pZ2amVPi
https://pastebin.com/vJsJjMev
https://pastebin.com/yVki2yWF
https://pastebin.com/MB1ap2h6

**Comment by RoleplayRascal** [comment]
wow pull it in then retardo

**Comment by chaosyourgod** [comment]
no u since I don't know how to tbh
